### PR TITLE
IMPROVED DOCS

### PR DESCRIPTION
**Pull request by amit007-majhi**

### CODE REVIEW

**Comment by hugovk** [comment]
@amit007-majhi  Please don't create lots of spam PRs for Hacktoberfest, it's against the rules and values, and not fair on maintainers.

https://hacktoberfest.digitalocean.com/details#spam

Maintainers: please label this `invalid` so it's not counted towards Hacktoberfest.

**Comment by pranayjoshi** [comment]
Please mark this as Spam

**Comment by pranayjoshi** [comment]
> @amit007-majhi Please don't create lots of spam PRs for Hacktoberfest, it's against the rules and values, and not fair on maintainers.
> 
> https://hacktoberfest.digitalocean.com/details#spam
> 
> Maintainers: please label this `invalid` so it's not counted towards Hacktoberfest.

I agree

**Comment by broken** [comment]
Thanks @hugovk and @pranayjoshi 

It looks like we got a few of these. I'll mark them as `invalid` and close them out. Let me know if there are other tags I should use.

**Comment by pranayjoshi** [comment]
> Thanks @hugovk and @pranayjoshi 
> 
> It looks like we got a few of these. I'll mark them as `invalid` and close them out. Let me know if there are other tags I should use.

No only the invalid tag is fine to mark it as a spam and just close it.

**Pull request closed without merging**
