### PR TITLE
Adding Indexing for Easy Navigation through README.md

### PR DESCRIPTION
**Pull request by pranayjoshi**
Solved ISSUE #411 
Added Anchor links For all Topics and Sub Topics.

### CODE REVIEW

**Review by MatejMecka — CHANGES_REQUESTED** [review]
A Markdown file can work both Online and Offline :) You may want to link to the paragraph instead of the URL.

**Comment by pranayjoshi** [comment]
> A Markdown file can work both Online and Offline :) You may want to link to the paragraph instead of the URL. 

Ohk thank you for the reply. I will surely do the changes

**Comment by pranayjoshi** [comment]
> A Markdown file can work both Online and Offline :) You may want to link to the paragraph instead of the URL.

Done

**Comment by broken** [comment]
Thanks for the change and signing the CLAs

**Comment by pranayjoshi** [comment]
Thank you sir.

**Comment by pranayjoshi** [comment]
Hi @broken . Now i dont think any more changes are required to this repo. So let's close it for now. Anyone who wants to open it. Feel free to open it.

**Pull request merged**
