### PR TITLE
fix export as saved model

### PR DESCRIPTION
**Pull request by fsx950223**
The module should be set as an attribute for export saved model

### CODE REVIEW

**Comment by broken** [comment]
Apologies for the review delay. I'm doing an audit now of incoming PRs as our notifications were not being properly filtered. This will be reviewed soon.

**Comment by broken** [comment]
This has been approved, but our linter is complaining. 

```
CheckLint found errors.
  Quote delimiter ' is inconsistent with the rest of the file [g-inconsistent-quotes]
	tensorflow_text/python/ops/hub_module_splitter_test.py:117
  Quote delimiter ' is inconsistent with the rest of the file [g-inconsistent-quotes]
	tensorflow_text/python/ops/hub_module_splitter_test.py:1118
```

Could you please update these quotes? Then we will be able to merge in the change. Thanks!

**Comment by fsx950223** [comment]
> This has been approved, but our linter is complaining.
> 
> ```
> CheckLint found errors.
>   Quote delimiter ' is inconsistent with the rest of the file [g-inconsistent-quotes]
> 	tensorflow_text/python/ops/hub_module_splitter_test.py:117
>   Quote delimiter ' is inconsistent with the rest of the file [g-inconsistent-quotes]
> 	tensorflow_text/python/ops/hub_module_splitter_test.py:1118
> ```
> 
> Could you please update these quotes? Then we will be able to merge in the change. Thanks!

Done

**Comment by broken** [comment]
Thanks!

**Pull request merged**
